// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repositories/message_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "chat-app/backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessageRepository) Create(ctx context.Context, message *entities.Message) (*entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(*entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMessageRepositoryMockRecorder) Create(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageRepository)(nil).Create), ctx, message)
}

// GetByRoomID mocks base method.
func (m *MockMessageRepository) GetByRoomID(ctx context.Context, roomID string, limit int) ([]*entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoomID", ctx, roomID, limit)
	ret0, _ := ret[0].([]*entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoomID indicates an expected call of GetByRoomID.
func (mr *MockMessageRepositoryMockRecorder) GetByRoomID(ctx, roomID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoomID", reflect.TypeOf((*MockMessageRepository)(nil).GetByRoomID), ctx, roomID, limit)
}

// StreamByRoomID mocks base method.
func (m *MockMessageRepository) StreamByRoomID(ctx context.Context, roomID string) (<-chan *entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamByRoomID", ctx, roomID)
	ret0, _ := ret[0].(<-chan *entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamByRoomID indicates an expected call of StreamByRoomID.
func (mr *MockMessageRepositoryMockRecorder) StreamByRoomID(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamByRoomID", reflect.TypeOf((*MockMessageRepository)(nil).StreamByRoomID), ctx, roomID)
}
