// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/message_usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "chat-app/backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageUseCase is a mock of MessageUseCase interface.
type MockMessageUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockMessageUseCaseMockRecorder
}

// MockMessageUseCaseMockRecorder is the mock recorder for MockMessageUseCase.
type MockMessageUseCaseMockRecorder struct {
	mock *MockMessageUseCase
}

// NewMockMessageUseCase creates a new mock instance.
func NewMockMessageUseCase(ctrl *gomock.Controller) *MockMessageUseCase {
	mock := &MockMessageUseCase{ctrl: ctrl}
	mock.recorder = &MockMessageUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageUseCase) EXPECT() *MockMessageUseCaseMockRecorder {
	return m.recorder
}

// GetMessageHistory mocks base method.
func (m *MockMessageUseCase) GetMessageHistory(ctx context.Context, roomID string, limit int) ([]*entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageHistory", ctx, roomID, limit)
	ret0, _ := ret[0].([]*entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageHistory indicates an expected call of GetMessageHistory.
func (mr *MockMessageUseCaseMockRecorder) GetMessageHistory(ctx, roomID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageHistory", reflect.TypeOf((*MockMessageUseCase)(nil).GetMessageHistory), ctx, roomID, limit)
}

// SendMessage mocks base method.
func (m *MockMessageUseCase) SendMessage(ctx context.Context, userID, username, content, roomID string) (*entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, userID, username, content, roomID)
	ret0, _ := ret[0].(*entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessageUseCaseMockRecorder) SendMessage(ctx, userID, username, content, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessageUseCase)(nil).SendMessage), ctx, userID, username, content, roomID)
}

// StreamMessages mocks base method.
func (m *MockMessageUseCase) StreamMessages(ctx context.Context, roomID string) (<-chan *entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamMessages", ctx, roomID)
	ret0, _ := ret[0].(<-chan *entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamMessages indicates an expected call of StreamMessages.
func (mr *MockMessageUseCaseMockRecorder) StreamMessages(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMessages", reflect.TypeOf((*MockMessageUseCase)(nil).StreamMessages), ctx, roomID)
}
